apiVersion: v1
kind: Service
metadata:
  name: alloy-faro-external
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: alloy
  ports:
  - name: faro
    port: 12347
    targetPort: 12347
    protocol: TCP
  type: LoadBalancer
