auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

  replication_factor: 1

  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2026-07-01
      store: tsdb
      object_store: azure
      schema: v13

      index:
        prefix: index_
        period: 24h

storage_config:
  azure:
    account_name: storagemonitoringlgtm
    account_key: 7PdsTWygD7cvLIOW76lpwNNZcK36HFBFhP637YPSOU/5zGsGcQSyDRP6It6CbDisuO3778l9PmY5+AStKnjGNQ==
    container_name: loki

  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache

compactor:
  working_directory: /loki/compactor

limits_config:
  allow_structured_metadata: false

analytics:
  reporting_enabled: false